FROM openjdk:17

WORKDIR /app
COPY target/*.jar app.jar

ENV DATABASE_URL ${DATABASE_URL}
ENV DATABASE_USERNAME ${DATABASE_USERNAME}
ENV DATABASE_PASSWORD ${DATABASE_PASSWORD}
ENV DATABASE_KEY ${API_KEY}
ENV DATABASE_URL ${API_URL}

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
